config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :shifts, only: [:create, :update, :destroy]
  get "shift-new", to: "shifts#new"
  resources :exchanges, only: [:create, :update] do
    get 'accepted_manager', to: 'exchanges#accept_manager!'
    get 'accepted_owner', to: 'exchanges#accept_user!'
    get 'refused_manager', to: 'exchanges#refuse_manager!'
  end
  get "dashboard", to: "dashboards#home", as: :dashboard
  get "supervise", to: "supervises#home", as: :supervise
  get "supervise/stat", to: "supervises#stat", as: :stat
  get "my-shifts", to: "dashboards#my_shifts", as: :my_shifts
  get "my-answers", to: "dashboards#my_answers", as: :my_answers
  get "dashboard/:shift_id/shift-answer", to: "exchanges#new", as: :shift_answer
end

app/views/shared/_bottom_navbar.html.erb
<div class="bottom_navbar">
  <div class="white"></div>
  <div class="grey py-2">
    <span><%= link_to "MES DEMANDES", my_shifts_path%></span>
    <p class="plus pb-3">
      <% if home %>
        <span><%= link_to "+", shift_new_path, id:"plus_icon"%></span>
      <% else %>
        <span><a href="/dashboard"><i id="plus_icon"class="fa fa-home"></i></a></span>
      <% end %>
    </p>
    <span><%= link_to "MES REPONSES", my_answers_path %></span>
  </div>
  <div class="black"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="96x96" href="<%= image_path 'icons/icon-96x96.png' %>">
<link rel="apple-touch-icon" sizes="128x128" href="<%= image_path 'icons/icon-128x128.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="192x192" href="<%= image_path 'icons/icon-192x192.png' %>">
<link rel="apple-touch-icon" sizes="384x384" href="<%= image_path 'icons/icon-384x384.png' %>">
<link rel="apple-touch-icon" sizes="512x512" href="<%= image_path 'icons/icon-512x512.png' %>">

app/views/shared/_main_card-detail.html.erb
<div class="container__detail-button flex justify-around w-9/12 mx-auto">
  <div class="detail-button__detail">
    <div class="detail-button__detail-owner flex justify-between items-center">
      <p class = "mr-2">Emetteur:</p>
      <p><%= "#{User.find(shift.user_id).first_name} #{User.find(shift.user_id).last_name}"%></p>
    </div>
    <div class="detail-button__detail-hours flex justify-between items-center">
      <p class = "mr-2">Heures travaillées:</p>
      <p><%= working_hours_to_h(shift) %></p>
    </div>
  </div>
    <%= link_to "ECHANGER", shift_answer_path(shift.id), class: 'button_action flex justify-center items-center' %>
</div>

app/views/shared/_main_card.html.erb
<div class="container__card-exchange flex justify-between items-center">
  <div class="card-exchange__line flex justify-center items-center">
    <h2> <%= Line.find(shift.line_id).name %></h2>
  </div>
    <h2><%= l(shift.date, format: "%a %e %b").upcase %></h2>
    <div class="card-exchange__hour-start" >
      <p>Début</p>
      <h3><%= shift.hour_start.strftime("%H:%M") %></h3>
    </div>
    <div class="card-exchange__hour-end">
      <p>Fin :</p>
      <h3><%= shift.hour_end.strftime("%H:%M") %></h3>
    </div>
    <% if avatar %>
      <%= image_tag shift.user.image, alt: "alttext", class: "card_avatar" %>
    <% end %>
</div>

app/views/shared/_main_card_answer-detail.html.erb
<div class="container__detail-button flex justify-around">
  <div class="detail-button__detail">
    <div class="detail-button__detail-owner flex justify-between items-center">
      <p class = "mr-2">Emetteur:</p>
      <p><%= "#{User.find(shift.user_id).first_name} #{User.find(shift.user_id).last_name}"%></p>
    </div>
    <div class="detail-button__detail-hours flex justify-between items-center">
      <p class = "mr-2">Heures travaillées:</p>
      <p><%= working_hours_to_h(shift) %></p>
    </div>
  </div>
    <%=link_to 'ACCEPTER', exchange_accepted_owner_path(exchange_id), class: "button_action"%>
</div>

app/views/shared/_main_card_answer.html.erb
<% if highlight %>
  <div class="card_answer highlight mb-1 ml-12">
<% else %>
  <div class="card_answer mb-1 ml-12">
<% end %>
  <div class="container__card-exchange flex justify-between items-center">
    <div class="card-exchange__line flex justify-center items-center">
      <h2> <%= Line.find(shift.line_id).name %></h2>
    </div>
      <h2><%= l(shift.date, format: "%a %e %b").upcase %></h2>
    <div class="card-exchange__hour-start" >
      <p>Début</p>
      <h3><%= shift.hour_start.strftime("%H:%M") %></h3>
    </div>
    <div class="card-exchange__hour-end">
      <p>Fin :</p>
      <h3><%= shift.hour_end.strftime("%H:%M") %></h3>
    </div>
    <% if avatar %>
      <%= image_tag shift.user.image, alt: "alttext", class: "card_avatar" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id = "phone_navbar" class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

    <span style= "color: white"><i class="fas fa-bars"></i> </span>
  </button>
  

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="navbar-custom">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link navbar-text"%>
      </li>
      <% else %>
      <li class="navbar-custom">
        <%= link_to "Login", new_user_session_path, class: "nav-link navbar-text" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_one_exchange-card.html.erb
<% if shift_of_current_user %>
  <div class= "one_exchange-card shift_of_current_user">
<% elsif validated %>
  <div class= "one_exchange-card validated">
<% else %>
  <div class= "one_exchange-card">
<% end %>
    <div class="line">
        <h2><%= shift.line.name %></h2>
    </div>
    <div class="date_hours">
      <div class="date">
        <h2><%= l(shift.date, format: "%a %e %b").upcase %></h2>
      </div>
      <div class ="shift_hours">
        <div class="starting_hour">
          <p id="start"> Début </p>
          <h3> <%= shift.hour_start.strftime('%H:%M') %></h3>
        </div>
        <div class="ending_hour">
          <p id="end"> Fin </p>
          <h3><%= shift.hour_end.strftime('%H:%M') %></h3>
        </div>
      </div>
    </div>
  </div>