config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :shifts, only: [:create, :update, :destroy]
  get "shift-new", to: "shifts#new"
  resources :exchanges, only: [:create, :update] do
    get 'accepted_manager', to: 'exchanges#accept_manager!'
    get 'accepted_owner', to: 'exchanges#accept_user!'
    get 'refused_manager', to: 'exchanges#refuse_manager!'
  end
  get "dashboard", to: "dashboards#home", as: :dashboard
  get "supervise", to: "supervises#home", as: :supervise
  get "supervise/stat", to: "supervises#stat", as: :stat
  get "my-shifts", to: "dashboards#my_shifts", as: :my_shifts
  get "my-answers", to: "dashboards#my_answers", as: :my_answers
  get "dashboard/:shift_id/shift-answer", to: "exchanges#new", as: :shift_answer
end

app/controllers/supervises_controller.rb
class SupervisesController < ApplicationController
  before_action :authenticate_user!

  def home
    @exchanges = Exchange.joins(joins_sql).where(where_sql_home, user_unit_id: current_user.unit_id).order(date: :asc)
  end

  def stat
    @exchanges = Exchange.joins(joins_sql).where(where_sql_stat, user_unit_id: current_user.unit_id).order(date: :desc)
    @lines = Unit.find(current_user.unit_id).lines
    if params[:date].present?
      @exchanges = @exchanges.select do |exchange|
        Shift.find(exchange.shift_owner_id).date.to_s == params[:date]
      end
    end

    if params[:line_id].present?
      @exchanges = @exchanges.select do |exchange|
        Shift.find(exchange.shift_owner_id).line_id == params[:line_id].to_i
      end
      # @exchanges = Exchange.where(line_id: params[:line_id])
    end

    if (params[:date].present? && params[:line_id].present?)
      @exchanges = @exchanges.select do |exchange|
        Shift.find(exchange.shift_owner_id).line_id == params[:line_id].to_i && Shift.find(exchange.shift_owner_id).date.to_s == params[:date]
      end
    end
  end


  private

  def joins_sql
    <<~SQL
      INNER JOIN shifts ON shifts.id = exchanges.shift_owner_id
      INNER JOIN users ON users.id = shifts.user_id
      INNER JOIN units ON units.id = users.unit_id
    SQL
  end

  def where_sql_home
    <<~SQL
      units.id = :user_unit_id AND
      accepted_owner IS TRUE AND
      accepted_manager IS NULL
    SQL
  end

  def where_sql_stat
    <<~SQL
      units.id = :user_unit_id AND
      accepted_owner IS TRUE AND
      accepted_manager IS NOT NULL
    SQL
  end
end

app/views/supervises/home.html.erb
<div class="my_container">
  <div class='flex justify-between mb-6'>
    <h1 class="titre_1 other">Supervision Dashboard</h1>
    <%= link_to "Historique", stat_path, class:"button_action hollow" %>
  </div>
  <% @exchanges.each do |exchange| %>
    <div class="exchange-review bg-gray-100 shadow-sm mb-4 rounded-lg">
      <p><strong>Exchange #<%= exchange.id %></strong></p>
      <div class="supervise_identities">
        <p><em><%= exchange.shift_owner.user.first_name %> <%= exchange.shift_owner.user.last_name %></em></p>
        <p><em><%= exchange.shift_answer.user.first_name %> <%= exchange.shift_answer.user.last_name %></em></p>
      </div>
      <div class ="exchange-review__overview">
        <div class= "exchange_cards">
          <div>
            <% shift_owner = Shift.find(exchange.shift_owner_id) %>
            <%= render partial: "shared/one_exchange-card", locals: { shift: shift_owner, shift_of_current_user: false, validated: false } %>
          </div>

          <div class="exchange_symbol">
            <i class="fas fa-exchange-alt"></i>
          </div>

          <div>
            <% shift_answer = Shift.find(exchange.shift_answer_id) %>
            <%= render partial: "shared/one_exchange-card", locals: { shift: shift_answer, shift_of_current_user: false, validated: false } %>
          </div>
        </div>
      </div>
      <br>
      <div class="exchange-review__manager-answer mx-2 px-2">
        <%= simple_form_for exchange, url: exchange_path(exchange.id), method: 'PATCH', html: { class: "flex mx-auto justify-between items-center" } do |f| %>
          <%= f.input :accepted_manager, as: :radio_buttons, collection: [[true, 'Oui'], [false, 'Non']], label_method: :second, value_method: :first, label: 'Réponse :' %>
          <%= f.input :message, label: 'Commentaires :', input_html: { id: 'manager-answer__message' } %>
          <%= f.submit 'Envoyer', class:"button_action" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/supervises/stat.html.erb
<div class="my_supervise_stats_container px-4">
  <div class='flex justify-between mb-10'>
    <h1 class="titre_1 other">Historique des demandes d'échange </h1>
    <%= link_to "Back to dashboard", supervise_path, class:"button_action hollow" %>
  </div>

  <h2 class="text-xl mb-6"><%= Unit.find(current_user.unit_id).name %></h1>

  <div class="results-filter my-6">
    <!-- Filtre par date -->
    <form action="/supervise/stat" method="get">
      <label for="line_id">Date :</label>
      <input type="date" name="date" class="mr-4 border-b border-gray-300 p-2 flatpickr">
      <!-- Filtre par line -->
      <label for="line_id">Ligne :</label>
      <select name="line_id" class="w-32 border-b border-gray-300 mr-4 p-2">
        <option value="" disabled selected></option>
        <% @lines.each do |line| %>
          <option value="<%= line.id %>"><%= line.name %></option>
        <% end %>
      </select>
      <button class="button_action">Filtrer</button>
    </form>
  </div>

  <div class="table_centrage table overflow-x-scroll">
    <table class="w-full">
      <thead>
        <tr class="text-sm">
          <th class="border-0 ">Id.</th>
          <th class="border-0 ">Date</th>
          <th class="border-0 ">Ligne</th>
          <th class="border-0 ">Demandeur</th>
          <th class="border-0 ">Répondant</th>
          <th class="border-0 ">Date de création</th>
          <th class="border-0 ">Date de validation</th>
          <th class="border-0 ">Message</th>
        </tr>
      </thead>
      <tbody>
        <% @exchanges.each do |exchange| %>
        <% shift_owner = Shift.find(exchange.shift_owner_id) %>
        <% shift_answer = Shift.find(exchange.shift_answer_id) %>
        <% date = shift_owner.date.strftime("%d/%m/%y") %>
        <% line = Line.find(shift_owner.line_id).name %>
        <tr class="text-sm">
          <td><%= exchange.id %></td>
          <td><%= date %></td>
          <td><%= line %></td>
          <td><%= "#{User.find(shift_owner.user_id).first_name} #{User.find(shift_owner.user_id).last_name}"%></td>
          <td><%= "#{User.find(shift_answer.user_id).first_name} #{User.find(shift_answer.user_id).last_name}"%></td>
          <td><%= exchange.created_at.strftime("%d/%m/%y") %></td>
          <td><%= exchange.updated_at.strftime("%d/%m/%y") %></td>
          <td><%= exchange.message %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>